name: voice_inc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+106

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  cloud_firestore: ^0.13.6
  firebase_messaging: ^6.0.16
  firebase_dynamic_links: ^0.5.1
  firebase_remote_config: ^0.3.1
  firebase_crashlytics: ^0.1.3+3

  flutter_user_agent: ^1.2.2
  flutter_secure_storage: ^3.3.5
  sqflite: ^1.3.2+1

  timeago: ^2.0.29
  intl: ^0.16.1
  share: ^0.6.5+4
  image_picker: ^0.6.7+14
  path: ^1.7.0
  path_provider: ^1.6.24
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  image_cropper: ^1.3.1
  url_launcher: ^5.7.10
  photo_view: ^0.10.3
  badges: ^1.1.4
  package_info: ^0.4.3+2
  flutter_holo_date_picker: ^0.3.0
  flutter_typeahead: ^1.9.0
  extended_text: ^4.0.0
  extended_text_field: ^5.0.2
  photo_manager: ^0.5.8
  video_trimmer: ^0.3.4
  video_player: ^1.0.1
  chewie: ^0.12.0
  flutter_rating_bar: ^3.0.1+1
  video_thumbnail: ^0.2.2
  diacritic: ^0.1.1
  html_character_entities: ^0.1.2+4
  uuid: ^2.2.2
  debounce_throttle: ^1.1.0
  cached_network_image: ^2.3.2+1
  story_view: ^0.12.4
  after_layout: ^1.0.7+2
  material_segmented_control: ^2.1.0
  permission_handler: ^5.0.1+1
  flutter_sound_lite: ^6.4.2+1
  flutter_beep: ^0.2.0
  vibration: ^1.7.2

  # Cambiar cuando compilas para producción
  video_compress: ^2.1.1
  #flutter_video_compress: ^0.3.7+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/galup_icon.png"
  adaptive_icon_background: "#722282"
  adaptive_icon_foreground: "dev_assets/galup_icon_adaptative.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locale/galup_es.json
    - assets/locale/galup_en.json
    - assets/logo.png
    - assets/splash.png
    - assets/background.png
    - assets/badge.png
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets/onboarding_4.png
    - assets/onboarding_5.png
  #   - images/a_dot_ham.jpeg
    - assets/videos/encuesta.mp4
    - assets/videos/tip.mp4
    - assets/videos/grupal.mp4
    - assets/videos/laboral.mp4
    - assets/videos/patrocinada.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  GalupFont
      fonts:
        - asset: assets/fonts/GalupFont.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages