/// Flutter icons GalupFont
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GalupFont
///      fonts:
///       - asset: fonts/GalupFont.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class GalupFont {
  GalupFont._();

  static const _kFontFam = 'GalupFont';
  static const _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certification = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_saved = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tips = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_select = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rango = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repost = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData challenge_1 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData survey = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_content = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tik_tok = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData challenge = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled_alt = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
